### ISSUE TITLE
DuplicatedSlotName #channelCredentials

### ISSUE THREAD

**Issue by robvanlopik** [psvensson/grpc-st#1]
Both in ComposedChannelCredentialsImpl and its superclass.
How can I load this anyway.

**Comment by psvensson** [comment]
I am sorry Rob, but this project doesn't work (yet, and possible never). I started to make a dent, but realized a bit in that HTTP 2 is needed for this to work at all. A better approach is probably to do FFI calls to the gRPC library for each platform, but that requires knowledge I don't have yet.  I have updated the README now to reflect the current status better.

**Comment by robvanlopik** [comment]
Hi Peter,
thanks for your swift reply. I hoped for a fast path to talking
toToit devices from Pharo. It seems more work would be needed.
The grpc.io site mentions that moost language implementations are
essentially wrappers around a basic piece of C-code, but even the wrappers
seem rather daunting.
I will have to think hard whether I should dive into this.
Thanks anyway. By the way, are you aware of any use of protocol buffers in
Pharo (I know the packages, but I am interested in how it is used).

**Comment by psvensson** [comment]
Hi Rob, yes I agree that the bets approach seems to be to call platform specific libraries instead of trying to re-implement everything. But it is also a bit too tough for me, and I honestly don't know of any working protobuf project for any smalltalk at the moment. 

I'll close this issue now, but please feel free to open a new one if needed, if ask directly in the pharo discord
